// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicFireInfo,
  DefaultFireInfoProps
} from "./plasmic/fire_spot/PlasmicFireInfo";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface FireInfoProps extends Omit<DefaultFireInfoProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultFireInfoProps altogether and have
// total control over the props for your component.
interface FireInfoProps extends DefaultFireInfoProps {}

function FireInfo_(props: FireInfoProps, ref: HTMLElementRefOf<"div">) {
  // Use PlasmicFireInfo to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicFireInfo are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all FireInfoProps here, but feel free
  // to do whatever works for you.

  return <PlasmicFireInfo root={{ ref }} {...props} />;
}

const FireInfo = React.forwardRef(FireInfo_);
export default FireInfo;
