// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iaGC8N7icN64RQS5kdk5ev
// Component: -70jaFn1U1
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_fire_spot.module.css"; // plasmic-import: iaGC8N7icN64RQS5kdk5ev/projectcss
import * as sty from "./PlasmicHomeIcon.module.css"; // plasmic-import: -70jaFn1U1/css

import HomeIcon from "./icons/PlasmicIcon__Home"; // plasmic-import: F1GpC1vB1p_/icon

export type PlasmicHomeIcon__VariantMembers = {};

export type PlasmicHomeIcon__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomeIcon__VariantsArgs;
export const PlasmicHomeIcon__VariantProps = new Array<VariantPropType>();

export type PlasmicHomeIcon__ArgsType = {};
type ArgPropType = keyof PlasmicHomeIcon__ArgsType;
export const PlasmicHomeIcon__ArgProps = new Array<ArgPropType>();

export type PlasmicHomeIcon__OverridesType = {
  root?: p.Flex<"svg">;
};

export interface DefaultHomeIconProps {
  className?: string;
}

function PlasmicHomeIcon__RenderFunc(props: {
  variants: PlasmicHomeIcon__VariantsArgs;
  args: PlasmicHomeIcon__ArgsType;
  overrides: PlasmicHomeIcon__OverridesType;
  dataFetches?: PlasmicHomeIcon__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <HomeIcon
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
      role={"img"}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomeIcon__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomeIcon__VariantsArgs;
    args?: PlasmicHomeIcon__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHomeIcon__Fetches;
  } & Omit<PlasmicHomeIcon__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomeIcon__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomeIcon__ArgProps,
      internalVariantPropNames: PlasmicHomeIcon__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHomeIcon__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomeIcon";
  } else {
    func.displayName = `PlasmicHomeIcon.${nodeName}`;
  }
  return func;
}

export const PlasmicHomeIcon = Object.assign(
  // Top-level PlasmicHomeIcon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicHomeIcon
    internalVariantProps: PlasmicHomeIcon__VariantProps,
    internalArgProps: PlasmicHomeIcon__ArgProps
  }
);

export default PlasmicHomeIcon;
/* prettier-ignore-end */
