// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iaGC8N7icN64RQS5kdk5ev
// Component: yIW795alBg
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_fire_spot.module.css"; // plasmic-import: iaGC8N7icN64RQS5kdk5ev/projectcss
import * as sty from "./PlasmicProfileIcon.module.css"; // plasmic-import: yIW795alBg/css

import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: saqBp-KweY/icon

export type PlasmicProfileIcon__VariantMembers = {};

export type PlasmicProfileIcon__VariantsArgs = {};
type VariantPropType = keyof PlasmicProfileIcon__VariantsArgs;
export const PlasmicProfileIcon__VariantProps = new Array<VariantPropType>();

export type PlasmicProfileIcon__ArgsType = {};
type ArgPropType = keyof PlasmicProfileIcon__ArgsType;
export const PlasmicProfileIcon__ArgProps = new Array<ArgPropType>();

export type PlasmicProfileIcon__OverridesType = {
  root?: p.Flex<"svg">;
};

export interface DefaultProfileIconProps {
  className?: string;
}

function PlasmicProfileIcon__RenderFunc(props: {
  variants: PlasmicProfileIcon__VariantsArgs;
  args: PlasmicProfileIcon__ArgsType;
  overrides: PlasmicProfileIcon__OverridesType;
  dataFetches?: PlasmicProfileIcon__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <VectorIcon
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
      role={"img"}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProfileIcon__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProfileIcon__VariantsArgs;
    args?: PlasmicProfileIcon__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicProfileIcon__Fetches;
  } & Omit<PlasmicProfileIcon__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicProfileIcon__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicProfileIcon__ArgProps,
      internalVariantPropNames: PlasmicProfileIcon__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicProfileIcon__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProfileIcon";
  } else {
    func.displayName = `PlasmicProfileIcon.${nodeName}`;
  }
  return func;
}

export const PlasmicProfileIcon = Object.assign(
  // Top-level PlasmicProfileIcon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicProfileIcon
    internalVariantProps: PlasmicProfileIcon__VariantProps,
    internalArgProps: PlasmicProfileIcon__ArgProps
  }
);

export default PlasmicProfileIcon;
/* prettier-ignore-end */
