// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iaGC8N7icN64RQS5kdk5ev
// Component: Lix0pM24ds
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_fire_spot.module.css"; // plasmic-import: iaGC8N7icN64RQS5kdk5ev/projectcss
import * as sty from "./PlasmicFire.module.css"; // plasmic-import: Lix0pM24ds/css

import ellipse4VUUuCAFzdV from "./images/ellipse4.svg"; // plasmic-import: vUUuC_aFzdV/picture

export type PlasmicFire__VariantMembers = {};

export type PlasmicFire__VariantsArgs = {};
type VariantPropType = keyof PlasmicFire__VariantsArgs;
export const PlasmicFire__VariantProps = new Array<VariantPropType>();

export type PlasmicFire__ArgsType = {};
type ArgPropType = keyof PlasmicFire__ArgsType;
export const PlasmicFire__ArgProps = new Array<ArgPropType>();

export type PlasmicFire__OverridesType = {
  root?: p.Flex<"img">;
};

export interface DefaultFireProps {
  className?: string;
}

function PlasmicFire__RenderFunc(props: {
  variants: PlasmicFire__VariantsArgs;
  args: PlasmicFire__ArgsType;
  overrides: PlasmicFire__OverridesType;
  dataFetches?: PlasmicFire__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <img
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      alt={""}
      className={classNames(defaultcss.img, projectcss.root_reset, sty.root)}
      role={"img"}
      src={ellipse4VUUuCAFzdV}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "img";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFire__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFire__VariantsArgs;
    args?: PlasmicFire__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicFire__Fetches;
  } & Omit<PlasmicFire__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicFire__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFire__ArgProps,
      internalVariantPropNames: PlasmicFire__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicFire__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFire";
  } else {
    func.displayName = `PlasmicFire.${nodeName}`;
  }
  return func;
}

export const PlasmicFire = Object.assign(
  // Top-level PlasmicFire renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicFire
    internalVariantProps: PlasmicFire__VariantProps,
    internalArgProps: PlasmicFire__ArgProps
  }
);

export default PlasmicFire;
/* prettier-ignore-end */
