// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iaGC8N7icN64RQS5kdk5ev
// Component: 8lZPU92Ytv
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_fire_spot.module.css"; // plasmic-import: iaGC8N7icN64RQS5kdk5ev/projectcss
import * as sty from "./PlasmicAlertBellIcon.module.css"; // plasmic-import: 8lZPU92Ytv/css

import Vector3Icon from "./icons/PlasmicIcon__Vector3"; // plasmic-import: lIZFbyKS7s/icon

export type PlasmicAlertBellIcon__VariantMembers = {};

export type PlasmicAlertBellIcon__VariantsArgs = {};
type VariantPropType = keyof PlasmicAlertBellIcon__VariantsArgs;
export const PlasmicAlertBellIcon__VariantProps = new Array<VariantPropType>();

export type PlasmicAlertBellIcon__ArgsType = {};
type ArgPropType = keyof PlasmicAlertBellIcon__ArgsType;
export const PlasmicAlertBellIcon__ArgProps = new Array<ArgPropType>();

export type PlasmicAlertBellIcon__OverridesType = {
  root?: p.Flex<"svg">;
};

export interface DefaultAlertBellIconProps {
  className?: string;
}

function PlasmicAlertBellIcon__RenderFunc(props: {
  variants: PlasmicAlertBellIcon__VariantsArgs;
  args: PlasmicAlertBellIcon__ArgsType;
  overrides: PlasmicAlertBellIcon__OverridesType;
  dataFetches?: PlasmicAlertBellIcon__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <Vector3Icon
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
      role={"img"}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAlertBellIcon__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAlertBellIcon__VariantsArgs;
    args?: PlasmicAlertBellIcon__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicAlertBellIcon__Fetches;
  } & Omit<PlasmicAlertBellIcon__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicAlertBellIcon__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAlertBellIcon__ArgProps,
      internalVariantPropNames: PlasmicAlertBellIcon__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicAlertBellIcon__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAlertBellIcon";
  } else {
    func.displayName = `PlasmicAlertBellIcon.${nodeName}`;
  }
  return func;
}

export const PlasmicAlertBellIcon = Object.assign(
  // Top-level PlasmicAlertBellIcon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicAlertBellIcon
    internalVariantProps: PlasmicAlertBellIcon__VariantProps,
    internalArgProps: PlasmicAlertBellIcon__ArgProps
  }
);

export default PlasmicAlertBellIcon;
/* prettier-ignore-end */
